<?php
/*
 * DetalaseApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace DetalaseApiLib\Tests;

use DetalaseApiLib\APIException;
use DetalaseApiLib\Exceptions;
use DetalaseApiLib\APIHelper;
use DetalaseApiLib\Models;

class AreaControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \DetalaseApiLib\Controllers\AreaController Controller instance
     */
    protected static $controller;

    /**
     * @var HttpCallBackCatcher Callback
     */
    protected $httpResponse;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass()
    {
        $client = new \DetalaseApiLib\DetalaseApiClient();
        self::$controller = $client->getArea();
    }

    /**
     * Setup test
     */
    protected function setUp()
    {
        $this->httpResponse = new HttpCallBackCatcher();
    }

    /**
     * TODO: Add Description
     */
    public function testGetProvince()
    {

        // Set callback and perform API call
        self::$controller->setHttpCallBack($this->httpResponse);
        try {
            self::$controller->getProvince();
        } catch (APIException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            $this->httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );
    }

    /**
     * key|value
---|---
province_id|id
city_id|id
     */
    public function testGetDistrict()
    {
        // Parameters for the API call
        $cityId = 1;

        // Set callback and perform API call
        self::$controller->setHttpCallBack($this->httpResponse);
        try {
            self::$controller->getDistrict($cityId);
        } catch (APIException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            $this->httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );
    }
}
