<?php
/*
 * DetalaseApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace DetalaseApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CostShipRequest implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var \DetalaseApiLib\Models\Person1 $person public property
     */
    public $person;

    /**
     * @todo Write general description for this property
     * @required
     * @var \DetalaseApiLib\Models\Product[] $product public property
     */
    public $product;

    /**
     * Constructor to set initial or default values of member properties
     * @param Person1 $person  Initialization value for $this->person
     * @param array   $product Initialization value for $this->product
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->person  = func_get_arg(0);
            $this->product = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['person']  = $this->person;
        $json['product'] = $this->product;

        return $json;
    }
}
