<?php
/*
 * DetalaseApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace DetalaseApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Person1 implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps province_id
     * @var string $provinceId public property
     */
    public $provinceId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps province_name
     * @var string $provinceName public property
     */
    public $provinceName;

    /**
     * @todo Write general description for this property
     * @required
     * @maps city_id
     * @var string $cityId public property
     */
    public $cityId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps city_name
     * @var string $cityName public property
     */
    public $cityName;

    /**
     * @todo Write general description for this property
     * @required
     * @maps sub_district_id
     * @var string $subDistrictId public property
     */
    public $subDistrictId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps sub_district_name
     * @var string $subDistrictName public property
     */
    public $subDistrictName;

    /**
     * @todo Write general description for this property
     * @required
     * @maps district_id
     * @var string $districtId public property
     */
    public $districtId;

    /**
     * @todo Write general description for this property
     * @required
     * @maps district_name
     * @var string $districtName public property
     */
    public $districtName;

    /**
     * @todo Write general description for this property
     * @required
     * @maps address_id
     * @var string $addressId public property
     */
    public $addressId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $address public property
     */
    public $address;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $phone public property
     */
    public $phone;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $provinceId      Initialization value for $this->provinceId
     * @param string $provinceName    Initialization value for $this->provinceName
     * @param string $cityId          Initialization value for $this->cityId
     * @param string $cityName        Initialization value for $this->cityName
     * @param string $subDistrictId   Initialization value for $this->subDistrictId
     * @param string $subDistrictName Initialization value for $this->subDistrictName
     * @param string $districtId      Initialization value for $this->districtId
     * @param string $districtName    Initialization value for $this->districtName
     * @param string $addressId       Initialization value for $this->addressId
     * @param string $name            Initialization value for $this->name
     * @param string $address         Initialization value for $this->address
     * @param string $phone           Initialization value for $this->phone
     */
    public function __construct()
    {
        if (12 == func_num_args()) {
            $this->provinceId      = func_get_arg(0);
            $this->provinceName    = func_get_arg(1);
            $this->cityId          = func_get_arg(2);
            $this->cityName        = func_get_arg(3);
            $this->subDistrictId   = func_get_arg(4);
            $this->subDistrictName = func_get_arg(5);
            $this->districtId      = func_get_arg(6);
            $this->districtName    = func_get_arg(7);
            $this->addressId       = func_get_arg(8);
            $this->name            = func_get_arg(9);
            $this->address         = func_get_arg(10);
            $this->phone           = func_get_arg(11);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['province_id']       = $this->provinceId;
        $json['province_name']     = $this->provinceName;
        $json['city_id']           = $this->cityId;
        $json['city_name']         = $this->cityName;
        $json['sub_district_id']   = $this->subDistrictId;
        $json['sub_district_name'] = $this->subDistrictName;
        $json['district_id']       = $this->districtId;
        $json['district_name']     = $this->districtName;
        $json['address_id']        = $this->addressId;
        $json['name']              = $this->name;
        $json['address']           = $this->address;
        $json['phone']             = $this->phone;

        return $json;
    }
}
