<?php
/*
 * DetalaseApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace DetalaseApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Person implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps address_id
     * @var integer $addressId public property
     */
    public $addressId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $address public property
     */
    public $address;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $phone public property
     */
    public $phone;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $addressId Initialization value for $this->addressId
     * @param string  $address   Initialization value for $this->address
     * @param string  $phone     Initialization value for $this->phone
     * @param string  $name      Initialization value for $this->name
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->addressId = func_get_arg(0);
            $this->address   = func_get_arg(1);
            $this->phone     = func_get_arg(2);
            $this->name      = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['address_id'] = $this->addressId;
        $json['address']    = $this->address;
        $json['phone']      = $this->phone;
        $json['name']       = $this->name;

        return $json;
    }
}
