<?php
/*
 * DetalaseApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace DetalaseApiLib;

use DetalaseApiLib\Controllers;

/**
 * DetalaseApiLib client class
 */
class DetalaseApiClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $oAuthAccessToken = null
    ) {
        Configuration::$oAuthAccessToken = $oAuthAccessToken ? $oAuthAccessToken : Configuration::$oAuthAccessToken;
    }
    /**
     * Singleton access to Auth controller
     * @return Controllers\AuthController The *Singleton* instance
     */
    public function getAuth()
    {
        return Controllers\AuthController::getInstance();
    }
    /**
     * Singleton access to Home controller
     * @return Controllers\HomeController The *Singleton* instance
     */
    public function getHome()
    {
        return Controllers\HomeController::getInstance();
    }
    /**
     * Singleton access to MyStore controller
     * @return Controllers\MyStoreController The *Singleton* instance
     */
    public function getMyStore()
    {
        return Controllers\MyStoreController::getInstance();
    }
    /**
     * Singleton access to Area controller
     * @return Controllers\AreaController The *Singleton* instance
     */
    public function getArea()
    {
        return Controllers\AreaController::getInstance();
    }
    /**
     * Singleton access to Wish controller
     * @return Controllers\WishController The *Singleton* instance
     */
    public function getWish()
    {
        return Controllers\WishController::getInstance();
    }
    /**
     * Singleton access to Product controller
     * @return Controllers\ProductController The *Singleton* instance
     */
    public function getProduct()
    {
        return Controllers\ProductController::getInstance();
    }
    /**
     * Singleton access to Cart controller
     * @return Controllers\CartController The *Singleton* instance
     */
    public function getCart()
    {
        return Controllers\CartController::getInstance();
    }
    /**
     * Singleton access to MyProduct controller
     * @return Controllers\MyProductController The *Singleton* instance
     */
    public function getMyProduct()
    {
        return Controllers\MyProductController::getInstance();
    }
    /**
     * Singleton access to Ship controller
     * @return Controllers\ShipController The *Singleton* instance
     */
    public function getShip()
    {
        return Controllers\ShipController::getInstance();
    }
    /**
     * Singleton access to Order controller
     * @return Controllers\OrderController The *Singleton* instance
     */
    public function getOrder()
    {
        return Controllers\OrderController::getInstance();
    }
}
