<?php
/*
 * DetalaseApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace DetalaseApiLib;

/**
 * Environments available for API
 */
class Environments
{
    /**
     * mobile
     */
    const PRODUCTION = "production";
}
